name: Build, test and analyze

on:
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:

  # Run linter to ensure new code respect coding rules
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - name: Setup metrics
        run: npm ci
      - name: Check contributions requirements
        run: npm run test-contrib
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
      - name: Run linter
        run: npm run linter

  # Build docker image from branch and run tests
  build:
    name: Build and test
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Format code with dprint
        run: |
          npm install -g dprint
          mkdir -v -p /home/runner/.cache/dprint/cache
          npx dprint fmt --config .github/config/dprint.json
      - name: Build Shadowghost/gh-metrics:${{ github.head_ref || 'master' }}
        env:
          GIT_REF: ${{ github.head_ref || 'master' }}
        run: docker build -t Shadowghost/gh-metrics:$(echo $GIT_REF | sed 's/[^a-z]/-/g') .
      - name: Run tests
        env:
          GIT_REF: ${{ github.head_ref || 'master' }}
        run: docker run --rm --entrypoint="" Shadowghost/gh-metrics:$(echo $GIT_REF | sed 's/[^a-z]/-/g') sh -xc 'npm install --no-save && exec npm run test-metrics'

  # Run CodeQL on branch
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Setup CodeQL
        uses: github/codeql-action/init@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3
        with:
          languages: javascript
          config-file: ./.github/config/codeql.yml
      - name: Analyze code
        uses: github/codeql-action/analyze@45580472a5bb82c4681c4ac726cfdb60060c2ee1 # v3
